# Generated by Django 3.1.1 on 2020-09-16 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baterias',
            fields=[
                ('amp', models.FloatField(blank=True, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'baterias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cidade', models.TextField(blank=True, null=True)),
                ('uf', models.TextField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('sigla', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Controladores',
            fields=[
                ('amp', models.FloatField(blank=True, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'controladores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inversores',
            fields=[
                ('pot', models.FloatField(blank=True, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inversores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('pot', models.FloatField(blank=True, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radiacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('jan', models.FloatField(blank=True, null=True)),
                ('fev', models.FloatField(blank=True, null=True)),
                ('mar', models.FloatField(blank=True, null=True)),
                ('abr', models.FloatField(blank=True, null=True)),
                ('mai', models.FloatField(blank=True, null=True)),
                ('jun', models.FloatField(blank=True, null=True)),
                ('jul', models.FloatField(blank=True, null=True)),
                ('ago', models.FloatField(blank=True, null=True)),
                ('sept', models.FloatField(blank=True, null=True)),
                ('out', models.FloatField(blank=True, null=True)),
                ('nov', models.FloatField(blank=True, null=True)),
                ('dez', models.FloatField(blank=True, null=True)),
                ('anual', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'radiacao',
                'managed': False,
            },
        ),
    ]
